Repository CardioKit/PeakWatch, pull requests merged in 2023-11, with the labels that each got.

#33 feature(PeakSwift): Update revision
  src/PeakWatch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: enhancement

#35 fix/race-condition
  src/PeakWatch/ViewModel/AlgorithmViewModel.swift
  src/PeakWatch/ViewModel/ExportViewModel.swift
Labels: bug

#34 Download and process test ECG
  .gitignore
  analysis/download_data.ipynb
Labels: enhancement

#38 Feature/stream based import
  README.md
  src/PeakWatch.xcodeproj/project.pbxproj
  src/PeakWatch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/PeakWatch/Error/ImportError.swift
  src/PeakWatch/Model/DTOs/ExportDTOs/ECGExportDTO.swift
  src/PeakWatch/Model/ECGSample.swift
  src/PeakWatch/Model/Streams/CSVImportStream.swift
  src/PeakWatch/Model/Streams/JSONExportStream.swift
  src/PeakWatch/Protocols/ExportStream.swift
  src/PeakWatch/Protocols/ExportableViewModel.swift
  src/PeakWatch/Protocols/FileExportable.swift
  src/PeakWatch/Protocols/ImportStream.swift
  src/PeakWatch/Utils/ECGExportDTOHelper.swift
  src/PeakWatch/Utils/FileNameHelper.swift
  src/PeakWatch/ViewModel/ExportInMemoryViewModel.swift
  src/PeakWatch/ViewModel/ExportStreamViewModel.swift
  src/PeakWatch/ViewModel/ImportViewModel.swift
  src/PeakWatch/Views/ECGList/ToolbarView/GlobalExportButtonView.swift
  src/PeakWatch/Views/Export/ExportProgressView.swift
  src/PeakWatch/Views/Export/ExportView.swift
  src/PeakWatch/Views/Export/ReportView.swift
  src/PeakWatch/Views/Import/ImportView.swift
Labels: enhancement, feature

#40 GitHub Protocol Change
  src/PeakWatch.xcodeproj/project.pbxproj
  src/PeakWatch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: bug

#41 Feature/f1 scores
  analysis/analysis.ipynb
Labels: enhancement
